### ISSUE TITLE
Second drivetrain motor on each side should use follow mode

### ISSUE THREAD

**Issue by blu28** [ToughTechs151/RapidReact2022#4]
NEO motors wih Spark Max controllers can be placed in "follow" mode which causes a motor to mimic what another motor does. When you have two motors on each side of a drivetrain, it makes sense to have the second follow the first. The consensus on Chief Delphi is that this is better than using a motorcontrollergroup or trying to control them all separately.

**Comment by kcq888** [comment]
Currently we are using MotorControllerGroup. We will take a look at the SparkMAX spec for the "follow" mode.

**Comment by blu28** [comment]
Moso was already intending to switch to follow mode, assigning this to him.

**Comment by kcq888** [comment]
We implemented the follow mode in the ChassisSubsystem.
