### ISSUE TITLE
The robot should be able to be driven in either tank drive mode or arcade drive mode.

### ISSUE THREAD

**Issue by blu28** [ToughTechs151/RapidReact2022#5]
Although we have usually used tank drive in the past, arcade drive is generally easier to control smoothly, and students who play video games are more likely to be familiar with the control. Also, it means that robot movement can be controlled from a single joystick. With the simplified mechanisms this year, it becomes feasible to have both functions performed by a single pilot. It would be desirable to be able to switch back and forth between the two modes, possibly using a physical switch on a DIO port or using the drive station.

**Comment by kcq888** [comment]
I have spoken to the driver team, and they don't know how to drive arcade drive mode. Another one for the bin list. We can consider after the drive team has a chance to drive the tank drive and we can consider if they want to try arcade drive.

**Comment by blu28** [comment]
They don't know how to use arcade drive because we have never coded it. Many teams have found it more intuitive and easier to use since it matches the control systems of most common video games. It has the advantage of requiring only one joystick and makes it easier to drive in a straight line. 

Alyssa, Jamie and I discussed it, and allowing for switching between the two modes is the solution we decided was best solution. As with the controller button issue, how it is implemented to be able to switch between them is negotiable. But   the ability to use arcade drive to control the robot is essential and since drive practice has already started, needed ASAP.

**Comment by kcq888** [comment]
Your comment is noted. We need to have discussion as a team. Since I was not part of the discussion, I could either agree or disagree with your proposal.

**Comment by blu28** [comment]
You were part of the discussion. I brought up using Arcade drive on our next bot at least three times in board meetings and no one objected then. I don't see you on the list of mentors involved in the Drive team, so I don't know why you would be expected to be sought out for the discussion. If you know of a technical reason why Software can not deliver this feature, then by all means enter your concern into the discussion, but indeed, looking at Moso's work in this it appears to be even easier than I at first thought. 

The decision as to whether or not we actually use Arcade mode in the competition is a discussion for the Drive Team to make after they have had time to practice with each mode. Whether or not the mode should be implemented is not a full team discussion. As I said, if you have a technical reason why it can't be implemented, then please say so.

**Comment by kcq888** [comment]
I don't recall there was a proposal regarding using Arcade drive. There was a discussion to use the code from Everybot and I know that the Everybot uses the Arcade drive pattern. I adopted our existing code from past year and implement the initial tank drive code. I did not make any comments about that it is a technical reason that we can't implement Arcade drive. All I want to make sure that the decision is being made by the drive team since they are the one who will be participating driving in the competition. Of course, we want to provide the comfortable experience of driving the Robot for the drive team. I also did not say that I object to the ideas either. In my first reply, I said that we would like the drive team try the tank drive first and we will consider implement the Arcade drive at a later time.

**Comment by blu28** [comment]
The discussions were prior to our decision to use the Everybot and had nothing to do with Everybot. It is exactly because we have used tank drive in the past that it is essential that arcade drive be made available immediately. If the team practices with tank drive and then later tries arcade drive, they will not want or be able to switch to arcade drive even if it is superior. On the other hand, switching from arcade to tank will likely be much easier for the same reason.

**Comment by kcq888** [comment]
We implemented this feature using Robot prefer. Closing this enhancement requested.
